puppet:
  image: puppet/puppetserver-standalone
  container_name: puppet
  hostname: puppet
  ports:
    - 8140:8140
  volumes:
    - "/etc/puppetlabs/code/"
postgres:
  image: puppet/puppetdb-postgres
  container_name: postgres
  hostname: postgres
  environment:
    POSTGRES_PASSWORD: puppetdb
    POSTGRES_USER: puppetdb
  ports:
    - 5432:5432
puppetdb:
  image: puppet/puppetdb
  hostname: puppetdb
  ports:
    - 8080:8080
puppetboard:
  image: puppet/puppetboard
  ports:
    - 8000:8000
puppetexplorer:
  image: puppet/puppetexplorer
  ports:
    - 80:80
puppetclient:
  image: puppet/puppet-agent-centos

