puppet:
  image: puppet/puppetserver-standalone
  hostname: puppet
  ports:
    - "8140"
  volumes:
    - "./code:/etc/puppetlabs/code/"
puppetdbpostgres:
  image: puppet/puppetdb-postgres
  environment:
    POSTGRES_PASSWORD: puppetdb
    POSTGRES_USER: puppetdb
  expose:
    - "5432"
puppetdb:
  image: puppet/puppetdb
  ports:
    - "8080"
    - "8081"
puppetboard:
  image: puppet/puppetboard
  ports:
    - "8000"
puppetexplorer:
  image: puppet/puppetexplorer
  ports:
    - "80"
