puppet:
  image: puppet/puppetserver-standalone
  container_name: puppet
  hostname: puppet
  ports:
    - 8140:8140
  volumes:
    - "/etc/puppetlabs/code/"
puppetdbpostgres:
  image: puppet/puppetdb-postgres
  container_name: postgres
  environment:
    POSTGRES_PASSWORD: puppetdb
    POSTGRES_USER: puppetdb
  expose:
    - 5432
puppetdb:
  image: puppet/puppetdb
  hostname: puppetdb
  ports:
    - 8080:8080
    - 8081:8081
  links: 
    - puppetdbpostgres:puppetdbpostgres
puppetboard:
  image: puppet/puppetboard
  ports:
    - 8000:8000
  links:
    - puppetdb:puppetdb
puppetexplorer:
  image: puppet/puppetexplorer
  ports:
    - 80:80
  links:
    - puppetdb:puppetdb
