name: Puppet
description: |
  # Description of the Catalog Entry
version: 1
category: # Category to be used for searching catalog entries
maintainer: # The maintainer of the catalog entry
license: # The license 
projectURL: # A URL related to the catalog entry
